/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/.well-known/openid-configuration": {
    /**
     * Retrieve OpenID Connect discovery metadata
     * @description Exposes the OpenID Connect discovery document so clients can locate Blerp endpoints automatically.
     */
    get: operations["getOpenIdConfiguration"];
  };
  "/.well-known/jwks.json": {
    /**
     * Retrieve JWKS (well-known)
     * @description Returns the JSON Web Key Set under the /.well-known path for standards-compliant OIDC verification.
     */
    get: operations["getWellKnownJwks"];
  };
  "/v1/jwks": {
    /**
     * Retrieve JWKS
     * @description Returns the service JWKS for automation workflows that cannot rely on the /.well-known path.
     */
    get: operations["getServiceJwks"];
  };
  "/v1/auth/signups": {
    /**
     * Create pending signup
     * @description Creates a signup intent and dispatches verification challenges for a new end user.
     */
    post: operations["createSignup"];
  };
  "/v1/auth/signups/{signup_id}/attempt": {
    /**
     * Complete verification for signup
     * @description Finalizes a pending signup by validating submitted verification factors.
     */
    post: operations["completeSignupVerification"];
  };
  "/v1/auth/oauth/{provider}": {
    /**
     * Initiate OAuth flow
     * @description Returns the authorization URL for the specified OAuth provider.
     */
    get: operations["initiateOAuth"];
  };
  "/v1/auth/oauth/{provider}/callback": {
    /**
     * OAuth callback
     * @description Handles the callback from an OAuth provider.
     */
    get: operations["oauthCallback"];
  };
  "/v1/auth/signins": {
    /**
     * Begin sign-in flow
     * @description Starts a sign-in attempt using the configured primary factor (password, OTP, or WebAuthn).
     */
    post: operations["beginSignin"];
  };
  "/v1/auth/signins/{signin_id}/attempt": {
    /**
     * Complete sign-in attempt
     * @description Validates a pending sign-in challenge and issues new session tokens on success.
     */
    post: operations["completeSignin"];
  };
  "/v1/sessions/{session_id}/revoke": {
    /**
     * Revoke a session
     * @description Immediately revokes a session so the associated devices must reauthenticate.
     */
    post: operations["revokeSession"];
  };
  "/v1/tokens/refresh": {
    /**
     * Exchange refresh token for access token
     * @description Trades a refresh token for a new pair of access/refresh tokens using the rotation policy.
     */
    post: operations["refreshSessionToken"];
  };
  "/v1/users": {
    /**
     * List users
     * @description Returns a paginated, filterable list of users for the active project.
     */
    get: operations["listUsers"];
    /**
     * Create user
     * @description Creates a user with initial profile data and credential state.
     */
    post: operations["createUser"];
  };
  "/v1/users/{user_id}": {
    /**
     * Retrieve user
     * @description Fetches a single user record including profile metadata and identities.
     */
    get: operations["getUser"];
    /**
     * Soft delete user
     * @description Soft deletes a user so they can be restored later but cannot authenticate.
     */
    delete: operations["deleteUser"];
    /**
     * Update user
     * @description Applies partial profile or metadata updates to a user.
     */
    patch: operations["updateUser"];
  };
  "/v1/users/{user_id}/email_addresses": {
    /**
     * List user email addresses
     * @description Returns all email addresses associated with a user.
     */
    get: operations["listUserEmailAddresses"];
    /**
     * Add email address
     * @description Adds a new email address to the user.
     */
    post: operations["addUserEmailAddress"];
  };
  "/v1/users/{user_id}/email_addresses/{email_address_id}": {
    /**
     * Delete email address
     * @description Removes an email address from the user.
     */
    delete: operations["deleteUserEmailAddress"];
  };
  "/v1/users/{user_id}/email_addresses/{email_address_id}/set_primary": {
    /**
     * Set primary email address
     * @description Sets an email address as the primary for the user.
     */
    post: operations["setPrimaryEmailAddress"];
  };
  "/v1/users/{user_id}/metadata": {
    /**
     * Update user metadata
     * @description Updates the public, private, or unsafe metadata for a user.
     */
    patch: operations["updateUserMetadata"];
  };
  "/v1/users/{user_id}/restore": {
    /**
     * Restore soft-deleted user
     * @description Restores a previously soft-deleted user and re-enables access.
     */
    post: operations["restoreUser"];
  };
  "/v1/users/{user_id}/identities/oauth": {
    /**
     * Link OAuth identity
     * @description Associates an external OAuth identity with the specified user for future logins.
     */
    post: operations["linkUserIdentity"];
  };
  "/v1/organizations": {
    /**
     * List organizations
     * @description Returns a paginated list of organizations in the current project.
     */
    get: operations["listOrganizations"];
    /**
     * Create organization
     * @description Creates a new organization along with optional role defaults.
     */
    post: operations["createOrganization"];
  };
  "/v1/organizations/{organization_id}": {
    /**
     * Retrieve organization
     * @description Fetches a single organization including metadata and member counts.
     */
    get: operations["getOrganization"];
    /**
     * Update organization settings
     * @description Updates organization metadata, membership requirements, or billing settings.
     */
    patch: operations["updateOrganization"];
    /**
     * Delete organization
     * @description Permanently deletes an organization and all associated memberships, invitations, and domains.
     */
    delete: operations["deleteOrganization"];
  };
  "/v1/organizations/{organization_id}/metadata": {
    /**
     * Update organization metadata
     * @description Updates the public or private metadata for an organization.
     */
    patch: operations["updateOrganizationMetadata"];
  };
  "/v1/organizations/{organization_id}/memberships": {
    /**
     * List memberships
     * @description Returns a list of memberships for the specified organization.
     */
    get: operations["listMemberships"];
    /**
     * Create membership
     * @description Adds a user to an organization with the provided roles.
     */
    post: operations["createMembership"];
  };
  "/v1/organizations/{organization_id}/memberships/{membership_id}": {
    /**
     * Delete membership
     * @description Removes a user from an organization.
     */
    delete: operations["deleteMembership"];
    /**
     * Update membership
     * @description Updates a membership's role or permissions.
     */
    patch: operations["updateMembership"];
  };
  "/v1/organizations/{organization_id}/roles": {
    /**
     * Update custom roles
     * @description Replaces the custom role definitions for an organization.
     */
    patch: operations["updateOrganizationRoles"];
  };
  "/v1/organizations/{organization_id}/domains": {
    /**
     * List organization domains
     * @description Retrieve all domains associated with an organization.
     */
    get: operations["listOrganizationDomains"];
    /**
     * Register organization domain
     * @description Register a new domain for an organization.
     */
    post: operations["registerOrganizationDomain"];
  };
  "/v1/organizations/{organization_id}/domains/{domain_id}": {
    /**
     * Delete organization domain
     * @description Remove a domain from an organization.
     */
    delete: operations["deleteOrganizationDomain"];
  };
  "/v1/organizations/{organization_id}/domains/{domain_id}/verify": {
    /**
     * Verify organization domain
     * @description Trigger verification of a domain ownership.
     */
    post: operations["verifyOrganizationDomain"];
  };
  "/v1/invitations": {
    /**
     * List invitations
     * @description Lists project invitations including pending, accepted, and expired states.
     */
    get: operations["listInvitations"];
    /**
     * Create invitation
     * @description Creates a new invitation for a user to join the project or organization.
     */
    post: operations["createInvitation"];
  };
  "/v1/invitations/{invitation_id}/revoke": {
    /**
     * Revoke invitation
     * @description Revokes an existing invitation so it can no longer be used.
     */
    post: operations["revokeInvitation"];
  };
  "/v1/users/{user_id}/mfa/totp": {
    /**
     * Enroll TOTP factor
     * @description Creates a TOTP factor for the user and returns shared secrets for enrollment.
     */
    post: operations["enrollTotp"];
  };
  "/v1/users/{user_id}/mfa/totp/verify": {
    /**
     * Verify TOTP enrollment
     * @description Verifies a pending TOTP enrollment by checking a generated passcode.
     */
    post: operations["verifyTotpEnrollment"];
  };
  "/v1/users/{user_id}/mfa/backup_codes/regenerate": {
    /**
     * Regenerate backup codes
     * @description Creates a new set of single-use backup codes for the user.
     */
    post: operations["regenerateBackupCodes"];
  };
  "/v1/users/{user_id}/mfa/webauthn": {
    /**
     * Register WebAuthn device
     * @description Starts a WebAuthn registration ceremony for the user.
     */
    post: operations["registerWebauthnDevice"];
  };
  "/v1/webhooks/endpoints": {
    /**
     * List webhook endpoints
     * @description Returns configured webhook endpoints for the project.
     */
    get: operations["listWebhookEndpoints"];
    /**
     * Create webhook endpoint
     * @description Creates a webhook endpoint and returns the signing secret.
     */
    post: operations["createWebhookEndpoint"];
  };
  "/v1/webhooks/endpoints/{endpoint_id}": {
    /**
     * Get webhook endpoint
     * @description Returns details for a specific webhook endpoint.
     */
    get: operations["getWebhookEndpoint"];
    /**
     * Delete webhook endpoint
     * @description Permanently removes a webhook endpoint.
     */
    delete: operations["deleteWebhookEndpoint"];
    /**
     * Update webhook endpoint
     * @description Updates the configuration for an existing webhook endpoint.
     */
    patch: operations["updateWebhookEndpoint"];
  };
  "/v1/webhooks/endpoints/{endpoint_id}/rotate_secret": {
    /**
     * Rotate webhook endpoint secret
     * @description Rotates the signing secret for a webhook endpoint while preserving its id.
     */
    post: operations["rotateWebhookSecret"];
  };
  "/v1/audit_logs": {
    /**
     * List audit log entries
     * @description Returns paginated audit log entries for compliance and monitoring.
     */
    get: operations["listAuditLogs"];
  };
  "/v1/events": {
    /**
     * List recent events
     * @description Lists recent event payloads for dashboards or streaming.
     */
    get: operations["listEvents"];
  };
  "/v1/config/theme": {
    /**
     * Retrieve theme configuration
     * @description Returns the hosted component theme configuration assigned to the project.
     */
    get: operations["getThemeConfig"];
    /**
     * Update theme configuration
     * @description Updates the theme configuration that powers hosted components.
     */
    put: operations["updateThemeConfig"];
  };
  "/v1/projects/{project_id}": {
    /**
     * Retrieve project configuration
     * @description Returns the project configuration used by APIs and dashboard flows.
     */
    get: operations["getProjectConfig"];
    /**
     * Update project configuration
     * @description Updates project-level configuration values and secrets.
     */
    put: operations["updateProjectConfig"];
    /**
     * Delete project
     * @description Permanently deletes a project and all associated data.
     */
    delete: operations["deleteProject"];
  };
  "/v1/projects/{project_id}/jwks": {
    /**
     * Rotate signing keys
     * @description Rotates the signing keys and returns updated JWKS metadata.
     */
    post: operations["rotateSigningKeys"];
  };
  "/v1/projects/{project_id}/keys": {
    /**
     * List API keys
     * @description Lists publishable and secret API keys scoped to the project.
     */
    get: operations["listApiKeys"];
    /**
     * Create API key
     * @description Creates an API key scoped to the requested permissions and environment.
     */
    post: operations["createApiKey"];
  };
  "/v1/projects/{project_id}/keys/{key_id}": {
    /**
     * Revoke API key
     * @description Revokes an API key, preventing it from being used for authentication.
     */
    delete: operations["revokeApiKey"];
  };
  "/v1/projects/{project_id}/keys/{key_id}/rotate": {
    /**
     * Rotate API key secret
     * @description Rotates the secret for an existing API key without changing the identifier.
     */
    post: operations["rotateApiKeySecret"];
  };
  "/v1/client": {
    /**
     * Retrieve publishable configuration
     * @description Returns the publishable configuration consumed directly by browser-based clients.
     */
    get: operations["getClientConfig"];
  };
  "/v1/client/sessions": {
    /**
     * Create session during SSR
     * @description Creates a session while rendering on the server and returns the cookie payload.
     */
    post: operations["createClientSession"];
  };
  "/v1/client/user": {
    /**
     * Retrieve current session user
     * @description Returns the current session's user to light-weight server actions or clients.
     */
    get: operations["getClientUser"];
  };
  "/v1/userinfo": {
    /**
     * Get user information
     * @description Returns OIDC compliant user information.
     */
    get: operations["getUserInfo"];
  };
  "/v1/sessions": {
    /**
     * List sessions
     * @description Retrieve all active sessions for the authenticated user.
     */
    get: operations["listSessions"];
  };
  "/v1/sessions/{session_id}": {
    /**
     * Delete a session
     * @description Immediately revokes and deletes a session by ID.
     */
    delete: operations["deleteSession"];
  };
  "/v1/usage": {
    /**
     * Get usage statistics
     * @description Retrieve resource usage and quota consumption for the tenant.
     */
    get: operations["getUsage"];
  };
  "/v1/auth/webauthn/passkeys": {
    /**
     * List passkeys
     * @description Retrieve all registered passkeys for the authenticated user.
     */
    get: operations["listPasskeys"];
  };
  "/v1/auth/webauthn/registration/options": {
    /**
     * Get WebAuthn registration options
     * @description Retrieve the options needed to register a new passkey.
     */
    get: operations["getWebauthnRegistrationOptions"];
  };
  "/v1/auth/webauthn/registration/verify": {
    /**
     * Verify WebAuthn registration
     * @description Complete passkey registration by verifying the attestation.
     */
    post: operations["verifyWebauthnRegistration"];
  };
  "/v1/users/{user_id}/identities": {
    /**
     * List user identities
     * @description Retrieve all OAuth and email identities linked to a user.
     */
    get: operations["listUserIdentities"];
  };
  "/v1/users/{user_id}/identities/oauth/{oauth_account_id}": {
    /**
     * Delete OAuth identity
     * @description Unlink an OAuth identity from a user account.
     */
    delete: operations["deleteUserOAuthIdentity"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    ErrorResponse: {
      error: {
        code: string;
        message: string;
        /** Format: uri */
        doc_url?: string;
        request_id?: string;
      };
    };
    PaginationMeta: {
      total?: number;
      next_cursor?: string;
      previous_cursor?: string;
    };
    EmailAddress: {
      /** Format: uuid */
      id: string;
      /** Format: email */
      email: string;
      verification: {
        /** @enum {string} */
        status: "unverified" | "pending" | "verified" | "failed";
        /** @enum {string} */
        strategy?: "email_code" | "email_link";
        attempts?: number;
        /** Format: date-time */
        last_attempted_at?: string;
      };
    };
    PhoneNumber: {
      /** Format: uuid */
      id: string;
      number: string;
      verification: components["schemas"]["EmailAddress"]["verification"];
    };
    PasskeyCredential: {
      id: string;
      friendly_name: string;
      transports: string[];
    };
    PublicMetadata: {
      [key: string]: unknown;
    };
    PrivateMetadata: {
      [key: string]: unknown;
    };
    UsageResponse: {
      users: number;
      organizations: number;
      sessions: number;
      limits: {
        maxUsers: number;
        maxOrganizations: number;
        maxSessions: number;
      };
    };
    User: {
      /** Format: uuid */
      id: string;
      external_id?: string;
      username?: string;
      first_name?: string;
      last_name?: string;
      /** Format: uri */
      image_url?: string;
      has_image?: boolean;
      /** Format: uuid */
      primary_email_id?: string;
      /** Format: uuid */
      primary_phone_id?: string;
      email_addresses: components["schemas"]["EmailAddress"][];
      phone_numbers?: components["schemas"]["PhoneNumber"][];
      passkeys?: components["schemas"]["PasskeyCredential"][];
      public_metadata?: components["schemas"]["PublicMetadata"];
      private_metadata?: components["schemas"]["PrivateMetadata"];
      unsafe_metadata?: components["schemas"]["PublicMetadata"];
      /** @enum {string} */
      status: "active" | "inactive" | "banned";
      locked?: boolean;
      /** @description Whether TOTP (authenticator app) is enabled for this user. */
      totp_enabled?: boolean;
      /** @description Whether backup codes are available for account recovery. */
      backup_code_enabled?: boolean;
      /** @description Whether any form of two-factor authentication is enabled. */
      two_factor_enabled?: boolean;
      /** Format: date-time */
      last_sign_in_at?: string;
      /** Format: date-time */
      created_at: string;
      /** Format: date-time */
      updated_at?: string;
      /** Format: date-time */
      deleted_at?: string;
    };
    Session: {
      id: string;
      /** Format: uuid */
      user_id: string;
      /** Format: uuid */
      organization_id?: string;
      /** @enum {string} */
      status: "active" | "revoked" | "expired";
      /** Format: date-time */
      active_at?: string;
      /** Format: date-time */
      expires_at?: string;
      /** Format: date-time */
      abandoned_at?: string;
      ip_address?: string;
      user_agent?: string;
      /** Format: date-time */
      latest_activity?: string;
      actor?: {
        /** @enum {string} */
        type?: "user" | "api_key";
        id?: string;
      };
      first_factor?: string;
      second_factor?: string;
      /** Format: date-time */
      last_rotated_at?: string;
      /** Format: date-time */
      created_at: string;
    };
    ThemeConfig: {
      /** @enum {string} */
      mode?: "light" | "dark" | "system";
      primary_color?: string;
      accent_color?: string;
      /** Format: uri */
      logo_url?: string;
      /** Format: uri */
      favicon_url?: string;
      font_family?: string;
      /** @enum {string} */
      button_shape?: "rounded" | "pill" | "sharp";
    };
    Project: {
      /** Format: uuid */
      id: string;
      /** Format: uuid */
      owner_user_id?: string;
      name: string;
      slug: string;
      environments?: ("development" | "staging" | "production")[];
      default_auth_strategies?: string[];
      allowed_origins?: string[];
      jwt_template?: {
        ttl_seconds?: number;
        custom_claims?: {
          [key: string]: unknown;
        };
      };
      branding?: {
        /** Format: uri */
        logo_url?: string;
        accent_color?: string;
      };
      theme?: components["schemas"]["ThemeConfig"];
      rate_limit_policy?: {
        requests_per_minute?: number;
        burst_size?: number;
      };
      feature_flags?: {
        [key: string]: unknown;
      };
      /** Format: date-time */
      created_at?: string;
      /** Format: date-time */
      updated_at?: string;
    };
    APIKey: {
      id: string;
      project_id: string;
      /** @enum {string} */
      environment: "development" | "staging" | "production";
      /** @enum {string} */
      type: "publishable" | "secret";
      scopes?: string[];
      prefix?: string;
      label?: string;
      /** @description Only returned when the key is generated or rotated. */
      secret?: string;
      /** @enum {string} */
      status: "active" | "revoked";
      /** Format: date-time */
      last_used_at?: string;
      /** Format: date-time */
      created_at: string;
      /** Format: date-time */
      rotated_at?: string;
    };
    Organization: {
      /** Format: uuid */
      id: string;
      /** Format: uuid */
      project_id: string;
      name: string;
      slug?: string;
      public_metadata?: {
        [key: string]: unknown;
      };
      private_metadata?: {
        [key: string]: unknown;
      };
      domains?: {
        domain?: string;
        /** @enum {string} */
        status?: "pending" | "verified" | "rejected";
        /** Format: date-time */
        verified_at?: string;
      }[];
      settings?: {
        allow_invites?: boolean;
        default_role?: string;
        /** @enum {string} */
        mfa_policy?: "optional" | "required" | "disabled";
      };
      /** Format: date-time */
      created_at?: string;
    };
    OrganizationDomain: {
      id: string;
      organization_id: string;
      domain: string;
      /** @enum {string} */
      verification_status: "verified" | "unverified";
      verification_token?: string;
      created_at?: number;
      updated_at?: number;
    };
    Membership: {
      /** Format: uuid */
      id: string;
      /** Format: uuid */
      organization_id: string;
      /** Format: uuid */
      user_id: string;
      role: string;
      permissions?: string[];
      /** Format: uuid */
      invited_by?: string;
      /** @enum {string} */
      status?: "active" | "revoked" | "pending_invite";
      /** Format: date-time */
      last_active_at?: string;
    };
    Invitation: {
      id: string;
      project_id?: string;
      organization_id: string;
      /** Format: email */
      email: string;
      role: string;
      permissions?: string[];
      inviter_user_id?: string;
      /** @enum {string} */
      status: "pending" | "accepted" | "revoked" | "expired";
      /** Format: uri */
      redirect_url?: string;
      /** Format: date-time */
      created_at: string;
      /** Format: date-time */
      expires_at: string;
      /** Format: date-time */
      accepted_at?: string;
    };
    Signup: {
      id: string;
      identifier?: string;
      /** @enum {string} */
      strategy: "password" | "magic_link" | "otp" | "passkey" | "oauth";
      /** @enum {string} */
      status: "needs_identifier" | "needs_verification" | "complete" | "abandoned";
      verification?: {
        /** @enum {string} */
        channel?: "email_code" | "email_link" | "sms";
        code?: string;
        /** Format: date-time */
        expires_at?: string;
      };
      created_session_id?: string;
      /** Format: date-time */
      expires_at?: string;
    };
    SigninAttempt: {
      id: string;
      identifier?: string;
      /** @enum {string} */
      status: "needs_first_factor" | "needs_second_factor" | "complete" | "locked";
      strategy?: string;
      mfa_required?: boolean;
      available_strategies?: string[];
      created_session_id?: string;
    };
    TokenResponse: {
      access_token: string;
      refresh_token?: string;
      expires_in: number;
      session_id: string;
      /** Format: date-time */
      issued_at?: string;
    };
    WebhookEndpoint: {
      /** Format: uuid */
      id: string;
      /** Format: uri */
      url: string;
      events: string[];
      secret?: string;
      /** @enum {string} */
      status?: "active" | "paused" | "failed";
      headers?: {
        [key: string]: string;
      };
      delivery_stats?: {
        success?: number;
        failure?: number;
        /** Format: date-time */
        last_failure?: string;
      };
      /** Format: date-time */
      created_at?: string;
    };
    Event: {
      id: string;
      type: string;
      version?: string;
      data: {
        [key: string]: unknown;
      };
      project_id?: string;
      /** Format: date-time */
      created_at?: string;
    };
    AuditLogEntry: {
      id: string;
      project_id: string;
      actor: {
        /** @enum {string} */
        type: "user" | "api_key" | "system";
        id: string;
        /** Format: email */
        email?: string;
      };
      action: string;
      resource: {
        type?: string;
        id?: string;
        display?: string;
      };
      metadata?: {
        [key: string]: unknown;
      };
      /** Format: date-time */
      created_at: string;
    };
    JWK: {
      kty: string;
      kid: string;
      use: string;
      alg: string;
      n?: string;
      e?: string;
      crv?: string;
      x?: string;
      y?: string;
    };
    JWKS: {
      keys: components["schemas"]["JWK"][];
    };
    OpenIDConfiguration: {
      /** Format: uri */
      issuer?: string;
      /** Format: uri */
      authorization_endpoint?: string;
      /** Format: uri */
      token_endpoint?: string;
      /** Format: uri */
      userinfo_endpoint?: string;
      /** Format: uri */
      jwks_uri?: string;
      response_types_supported?: string[];
      subject_types_supported?: string[];
      scopes_supported?: string[];
      id_token_signing_alg_values_supported?: string[];
      token_endpoint_auth_methods_supported?: string[];
    };
  };
  responses: {
    /** @description Bad request */
    BadRequest: {
      content: {
        "application/json": components["schemas"]["ErrorResponse"];
      };
    };
  };
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {
  /**
   * Retrieve OpenID Connect discovery metadata
   * @description Exposes the OpenID Connect discovery document so clients can locate Blerp endpoints automatically.
   */
  getOpenIdConfiguration: {
    responses: {
      /** @description Discovery metadata */
      200: {
        content: {
          "application/json": components["schemas"]["OpenIDConfiguration"];
        };
      };
    };
  };
  /**
   * Retrieve JWKS (well-known)
   * @description Returns the JSON Web Key Set under the /.well-known path for standards-compliant OIDC verification.
   */
  getWellKnownJwks: {
    responses: {
      /** @description JSON Web Key Set */
      200: {
        content: {
          "application/json": components["schemas"]["JWKS"];
        };
      };
    };
  };
  /**
   * Retrieve JWKS
   * @description Returns the service JWKS for automation workflows that cannot rely on the /.well-known path.
   */
  getServiceJwks: {
    responses: {
      /** @description JSON Web Key Set */
      200: {
        content: {
          "application/json": components["schemas"]["JWKS"];
        };
      };
    };
  };
  /**
   * Create pending signup
   * @description Creates a signup intent and dispatches verification challenges for a new end user.
   */
  createSignup: {
    requestBody: {
      content: {
        "application/json": {
          /** Format: email */
          email?: string;
          phone?: string;
          password?: string;
          /** @enum {string} */
          strategy: "password" | "magic_link" | "otp" | "passkey" | "oauth";
        };
      };
    };
    responses: {
      /** @description Signup created */
      201: {
        content: {
          "application/json": components["schemas"]["Signup"];
        };
      };
      /** @description Invalid request */
      400: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  /**
   * Complete verification for signup
   * @description Finalizes a pending signup by validating submitted verification factors.
   */
  completeSignupVerification: {
    parameters: {
      path: {
        signup_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": {
          code?: string;
          token?: string;
          webauthn_response?: {
            [key: string]: unknown;
          };
        };
      };
    };
    responses: {
      /** @description Signup completed */
      200: {
        content: {
          "application/json": {
            user_id?: string;
          };
        };
      };
    };
  };
  /**
   * Initiate OAuth flow
   * @description Returns the authorization URL for the specified OAuth provider.
   */
  initiateOAuth: {
    parameters: {
      query: {
        redirect_uri: string;
      };
      path: {
        provider: "github" | "google" | "discord";
      };
    };
    responses: {
      /** @description Authorization URL */
      200: {
        content: {
          "application/json": {
            /** Format: uri */
            url?: string;
          };
        };
      };
    };
  };
  /**
   * OAuth callback
   * @description Handles the callback from an OAuth provider.
   */
  oauthCallback: {
    parameters: {
      query: {
        code: string;
        state?: string;
      };
      path: {
        provider: string;
      };
    };
    responses: {
      /** @description OAuth login successful */
      200: components["responses"]["BadRequest"];
    };
  };
  /**
   * Begin sign-in flow
   * @description Starts a sign-in attempt using the configured primary factor (password, OTP, or WebAuthn).
   */
  beginSignin: {
    requestBody: {
      content: {
        "application/json": {
          identifier: string;
          /** @enum {string} */
          strategy: "password" | "magic_link" | "otp" | "passkey" | "oauth";
        };
      };
    };
    responses: {
      /** @description Sign-in attempt created */
      201: {
        content: {
          "application/json": components["schemas"]["SigninAttempt"];
        };
      };
      400: components["responses"]["BadRequest"];
    };
  };
  /**
   * Complete sign-in attempt
   * @description Validates a pending sign-in challenge and issues new session tokens on success.
   */
  completeSignin: {
    parameters: {
      path: {
        signin_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": {
          password?: string;
          code?: string;
          webauthn_response?: {
            [key: string]: unknown;
          };
        };
      };
    };
    responses: {
      /** @description Sign-in completed */
      200: {
        content: {
          "application/json": {
            session: components["schemas"]["Session"];
            tokens: components["schemas"]["TokenResponse"];
          };
        };
      };
      400: components["responses"]["BadRequest"];
    };
  };
  /**
   * Revoke a session
   * @description Immediately revokes a session so the associated devices must reauthenticate.
   */
  revokeSession: {
    parameters: {
      path: {
        session_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": {
          reason?: string;
        };
      };
    };
    responses: {
      /** @description Revoked */
      204: {
        content: never;
      };
      400: components["responses"]["BadRequest"];
    };
  };
  /**
   * Exchange refresh token for access token
   * @description Trades a refresh token for a new pair of access/refresh tokens using the rotation policy.
   */
  refreshSessionToken: {
    requestBody: {
      content: {
        "application/json": {
          refresh_token: string;
        };
      };
    };
    responses: {
      /** @description Token response */
      200: {
        content: {
          "application/json": components["schemas"]["TokenResponse"];
        };
      };
      400: components["responses"]["BadRequest"];
    };
  };
  /**
   * List users
   * @description Returns a paginated, filterable list of users for the active project.
   */
  listUsers: {
    parameters: {
      query?: {
        email?: string;
        created_before?: string;
        created_after?: string;
        status?: "active" | "inactive" | "banned";
        /** @description JSON pointer style path under public/private metadata. */
        metadata_key?: string;
        /** @description Value to match for the provided metadata_key. */
        metadata_value?: string;
        limit?: number;
        cursor?: string;
      };
    };
    responses: {
      /** @description Users list */
      200: {
        content: {
          "application/json": {
            data: components["schemas"]["User"][];
            meta?: components["schemas"]["PaginationMeta"];
          };
        };
      };
    };
  };
  /**
   * Create user
   * @description Creates a user with initial profile data and credential state.
   */
  createUser: {
    requestBody: {
      content: {
        "application/json": {
          email_addresses?: string[];
          phone_numbers?: string[];
          password?: string;
          public_metadata?: components["schemas"]["PublicMetadata"];
          private_metadata?: components["schemas"]["PrivateMetadata"];
        };
      };
    };
    responses: {
      /** @description User created */
      201: {
        content: {
          "application/json": components["schemas"]["User"];
        };
      };
      400: components["responses"]["BadRequest"];
    };
  };
  /**
   * Retrieve user
   * @description Fetches a single user record including profile metadata and identities.
   */
  getUser: {
    parameters: {
      path: {
        user_id: string;
      };
    };
    responses: {
      /** @description User details */
      200: {
        content: {
          "application/json": components["schemas"]["User"];
        };
      };
      /** @description Not found */
      404: {
        content: never;
      };
    };
  };
  /**
   * Soft delete user
   * @description Soft deletes a user so they can be restored later but cannot authenticate.
   */
  deleteUser: {
    parameters: {
      path: {
        user_id: string;
      };
    };
    responses: {
      /** @description Deleted */
      204: {
        content: never;
      };
    };
  };
  /**
   * Update user
   * @description Applies partial profile or metadata updates to a user.
   */
  updateUser: {
    parameters: {
      path: {
        user_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": {
          first_name?: string;
          last_name?: string;
          username?: string;
          public_metadata?: components["schemas"]["PublicMetadata"];
          private_metadata?: components["schemas"]["PrivateMetadata"];
          password?: string;
          /** @enum {string} */
          status?: "active" | "inactive" | "banned";
        };
      };
    };
    responses: {
      /** @description Updated user */
      200: {
        content: {
          "application/json": components["schemas"]["User"];
        };
      };
    };
  };
  /**
   * List user email addresses
   * @description Returns all email addresses associated with a user.
   */
  listUserEmailAddresses: {
    parameters: {
      path: {
        user_id: string;
      };
    };
    responses: {
      /** @description Email addresses */
      200: {
        content: {
          "application/json": {
            data?: components["schemas"]["EmailAddress"][];
          };
        };
      };
    };
  };
  /**
   * Add email address
   * @description Adds a new email address to the user.
   */
  addUserEmailAddress: {
    parameters: {
      path: {
        user_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": {
          /** Format: email */
          email: string;
        };
      };
    };
    responses: {
      /** @description Email address added */
      201: {
        content: {
          "application/json": components["schemas"]["EmailAddress"];
        };
      };
    };
  };
  /**
   * Delete email address
   * @description Removes an email address from the user.
   */
  deleteUserEmailAddress: {
    parameters: {
      path: {
        user_id: string;
        email_address_id: string;
      };
    };
    responses: {
      /** @description Email address deleted */
      204: {
        content: never;
      };
    };
  };
  /**
   * Set primary email address
   * @description Sets an email address as the primary for the user.
   */
  setPrimaryEmailAddress: {
    parameters: {
      path: {
        user_id: string;
        email_address_id: string;
      };
    };
    responses: {
      /** @description Primary email set */
      200: {
        content: {
          "application/json": components["schemas"]["EmailAddress"];
        };
      };
    };
  };
  /**
   * Update user metadata
   * @description Updates the public, private, or unsafe metadata for a user.
   */
  updateUserMetadata: {
    parameters: {
      path: {
        user_id: string;
      };
    };
    requestBody?: {
      content: {
        "application/json": {
          public_metadata?: {
            [key: string]: unknown;
          };
          private_metadata?: {
            [key: string]: unknown;
          };
          unsafe_metadata?: {
            [key: string]: unknown;
          };
        };
      };
    };
    responses: {
      /** @description Updated user */
      200: {
        content: {
          "application/json": components["schemas"]["User"];
        };
      };
    };
  };
  /**
   * Restore soft-deleted user
   * @description Restores a previously soft-deleted user and re-enables access.
   */
  restoreUser: {
    parameters: {
      path: {
        user_id: string;
      };
    };
    responses: {
      /** @description Restored user */
      200: {
        content: {
          "application/json": components["schemas"]["User"];
        };
      };
    };
  };
  /**
   * Link OAuth identity
   * @description Associates an external OAuth identity with the specified user for future logins.
   */
  linkUserIdentity: {
    parameters: {
      path: {
        user_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": {
          provider: string;
          provider_user_id: string;
          access_token?: string;
          refresh_token?: string;
          /** Format: date-time */
          expires_at?: string;
        };
      };
    };
    responses: {
      /** @description Linked */
      200: {
        content: never;
      };
    };
  };
  /**
   * List organizations
   * @description Returns a paginated list of organizations in the current project.
   */
  listOrganizations: {
    parameters: {
      query?: {
        project_id?: string;
        domain?: string;
        cursor?: string;
      };
    };
    responses: {
      /** @description Organizations list */
      200: {
        content: {
          "application/json": {
            data?: components["schemas"]["Organization"][];
            meta?: components["schemas"]["PaginationMeta"];
          };
        };
      };
    };
  };
  /**
   * Create organization
   * @description Creates a new organization along with optional role defaults.
   */
  createOrganization: {
    requestBody: {
      content: {
        "application/json": {
          project_id: string;
          name: string;
          slug?: string;
        };
      };
    };
    responses: {
      /** @description Organization created */
      201: {
        content: {
          "application/json": components["schemas"]["Organization"];
        };
      };
    };
  };
  /**
   * Retrieve organization
   * @description Fetches a single organization including metadata and member counts.
   */
  getOrganization: {
    parameters: {
      path: {
        organization_id: string;
      };
    };
    responses: {
      /** @description Organization */
      200: {
        content: {
          "application/json": components["schemas"]["Organization"];
        };
      };
    };
  };
  /**
   * Update organization settings
   * @description Updates organization metadata, membership requirements, or billing settings.
   */
  updateOrganization: {
    parameters: {
      path: {
        organization_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": {
          metadata_public?: {
            [key: string]: unknown;
          };
          metadata_private?: {
            [key: string]: unknown;
          };
          settings?: Record<string, never>;
        };
      };
    };
    responses: {
      /** @description Updated organization */
      200: {
        content: {
          "application/json": components["schemas"]["Organization"];
        };
      };
    };
  };
  /**
   * Delete organization
   * @description Permanently deletes an organization and all associated data.
   */
  deleteOrganization: {
    parameters: {
      path: {
        organization_id: string;
      };
    };
    responses: {
      /** @description Organization deleted */
      204: {
        content: never;
      };
    };
  };
  /**
   * Update organization metadata
   * @description Updates the public or private metadata for an organization.
   */
  updateOrganizationMetadata: {
    parameters: {
      path: {
        organization_id: string;
      };
    };
    requestBody?: {
      content: {
        "application/json": {
          public_metadata?: {
            [key: string]: unknown;
          };
          private_metadata?: {
            [key: string]: unknown;
          };
        };
      };
    };
    responses: {
      /** @description Updated organization */
      200: {
        content: {
          "application/json": components["schemas"]["Organization"];
        };
      };
    };
  };
  /**
   * List memberships
   * @description Returns a list of memberships for the specified organization.
   */
  listMemberships: {
    parameters: {
      path: {
        organization_id: string;
      };
    };
    responses: {
      /** @description List of memberships */
      200: {
        content: {
          "application/json": {
            data?: components["schemas"]["Membership"][];
          };
        };
      };
    };
  };
  /**
   * Create membership
   * @description Adds a user to an organization with the provided roles.
   */
  createMembership: {
    parameters: {
      path: {
        organization_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": {
          user_id: string;
          role: string;
        };
      };
    };
    responses: {
      /** @description Membership created */
      201: {
        content: {
          "application/json": components["schemas"]["Membership"];
        };
      };
    };
  };
  /**
   * Delete membership
   * @description Removes a user from an organization.
   */
  deleteMembership: {
    parameters: {
      path: {
        organization_id: string;
        membership_id: string;
      };
    };
    responses: {
      /** @description Membership deleted */
      204: {
        content: never;
      };
      /** @description Not found */
      404: {
        content: never;
      };
    };
  };
  /**
   * Update membership
   * @description Updates a membership's role or permissions.
   */
  updateMembership: {
    parameters: {
      path: {
        organization_id: string;
        membership_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": {
          role?: string;
          permissions?: string[];
        };
      };
    };
    responses: {
      /** @description Membership updated */
      200: {
        content: {
          "application/json": components["schemas"]["Membership"];
        };
      };
      /** @description Not found */
      404: {
        content: never;
      };
    };
  };
  /**
   * Update custom roles
   * @description Replaces the custom role definitions for an organization.
   */
  updateOrganizationRoles: {
    parameters: {
      path: {
        organization_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": {
          roles?: {
            name?: string;
            permissions?: string[];
          }[];
        };
      };
    };
    responses: {
      /** @description Updated roles */
      200: {
        content: never;
      };
    };
  };
  /**
   * List organization domains
   * @description Retrieve all domains associated with an organization.
   */
  listOrganizationDomains: {
    parameters: {
      path: {
        organization_id: string;
      };
    };
    responses: {
      /** @description List of domains */
      200: {
        content: {
          "application/json": {
            data?: components["schemas"]["OrganizationDomain"][];
          };
        };
      };
    };
  };
  /**
   * Register organization domain
   * @description Register a new domain for an organization.
   */
  registerOrganizationDomain: {
    parameters: {
      path: {
        organization_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": {
          domain: string;
        };
      };
    };
    responses: {
      /** @description Domain registered */
      201: {
        content: {
          "application/json": components["schemas"]["OrganizationDomain"];
        };
      };
    };
  };
  /**
   * Delete organization domain
   * @description Remove a domain from an organization.
   */
  deleteOrganizationDomain: {
    parameters: {
      path: {
        organization_id: string;
        domain_id: string;
      };
    };
    responses: {
      /** @description Domain deleted */
      204: {
        content: never;
      };
    };
  };
  /**
   * Verify organization domain
   * @description Trigger verification of a domain ownership.
   */
  verifyOrganizationDomain: {
    parameters: {
      path: {
        organization_id: string;
        domain_id: string;
      };
    };
    responses: {
      /** @description Domain verified */
      200: {
        content: {
          "application/json": components["schemas"]["OrganizationDomain"];
        };
      };
    };
  };
  /**
   * List invitations
   * @description Lists project invitations including pending, accepted, and expired states.
   */
  listInvitations: {
    parameters: {
      query?: {
        email?: string;
        organization_id?: string;
        status?: "pending" | "accepted" | "revoked" | "expired";
        cursor?: string;
        limit?: number;
      };
    };
    responses: {
      /** @description Invitations */
      200: {
        content: {
          "application/json": {
            data?: components["schemas"]["Invitation"][];
            meta?: components["schemas"]["PaginationMeta"];
          };
        };
      };
    };
  };
  /**
   * Create invitation
   * @description Creates a new invitation for a user to join the project or organization.
   */
  createInvitation: {
    requestBody: {
      content: {
        "application/json": {
          /** Format: email */
          email: string;
          organization_id: string;
          role: string;
          permissions?: string[];
          /** Format: date-time */
          expires_at?: string;
          /** Format: uri */
          redirect_url?: string;
        };
      };
    };
    responses: {
      /** @description Invitation created */
      201: {
        content: {
          "application/json": components["schemas"]["Invitation"];
        };
      };
    };
  };
  /**
   * Revoke invitation
   * @description Revokes an existing invitation so it can no longer be used.
   */
  revokeInvitation: {
    parameters: {
      path: {
        invitation_id: string;
      };
    };
    requestBody?: {
      content: {
        "application/json": {
          reason?: string;
        };
      };
    };
    responses: {
      /** @description Invitation revoked */
      200: {
        content: {
          "application/json": components["schemas"]["Invitation"];
        };
      };
      /** @description Not found */
      404: {
        content: never;
      };
    };
  };
  /**
   * Enroll TOTP factor
   * @description Creates a TOTP factor for the user and returns shared secrets for enrollment.
   */
  enrollTotp: {
    parameters: {
      path: {
        user_id: string;
      };
    };
    responses: {
      /** @description TOTP secret created */
      201: {
        content: never;
      };
    };
  };
  /**
   * Verify TOTP enrollment
   * @description Verifies a pending TOTP enrollment by checking a generated passcode.
   */
  verifyTotpEnrollment: {
    parameters: {
      path: {
        user_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": {
          code: string;
        };
      };
    };
    responses: {
      /** @description Verified */
      200: {
        content: never;
      };
    };
  };
  /**
   * Regenerate backup codes
   * @description Creates a new set of single-use backup codes for the user.
   */
  regenerateBackupCodes: {
    parameters: {
      path: {
        user_id: string;
      };
    };
    responses: {
      /** @description Codes regenerated */
      200: {
        content: {
          "application/json": {
            codes?: string[];
          };
        };
      };
    };
  };
  /**
   * Register WebAuthn device
   * @description Starts a WebAuthn registration ceremony for the user.
   */
  registerWebauthnDevice: {
    parameters: {
      path: {
        user_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": {
          attestation: {
            [key: string]: unknown;
          };
        };
      };
    };
    responses: {
      /** @description Device registered */
      201: {
        content: never;
      };
    };
  };
  /**
   * List webhook endpoints
   * @description Returns configured webhook endpoints for the project.
   */
  listWebhookEndpoints: {
    responses: {
      /** @description Webhook endpoints */
      200: {
        content: {
          "application/json": {
            data?: components["schemas"]["WebhookEndpoint"][];
          };
        };
      };
    };
  };
  /**
   * Create webhook endpoint
   * @description Creates a webhook endpoint and returns the signing secret.
   */
  createWebhookEndpoint: {
    requestBody: {
      content: {
        "application/json": {
          /** Format: uri */
          url: string;
          events: string[];
        };
      };
    };
    responses: {
      /** @description Endpoint created */
      201: {
        content: {
          "application/json": components["schemas"]["WebhookEndpoint"];
        };
      };
    };
  };
  /**
   * Get webhook endpoint
   * @description Returns details for a specific webhook endpoint.
   */
  getWebhookEndpoint: {
    parameters: {
      path: {
        endpoint_id: string;
      };
    };
    responses: {
      /** @description Webhook endpoint */
      200: {
        content: {
          "application/json": components["schemas"]["WebhookEndpoint"];
        };
      };
    };
  };
  /**
   * Delete webhook endpoint
   * @description Permanently removes a webhook endpoint.
   */
  deleteWebhookEndpoint: {
    parameters: {
      path: {
        endpoint_id: string;
      };
    };
    responses: {
      /** @description Deleted */
      204: {
        content: never;
      };
    };
  };
  /**
   * Update webhook endpoint
   * @description Updates the configuration for an existing webhook endpoint.
   */
  updateWebhookEndpoint: {
    parameters: {
      path: {
        endpoint_id: string;
      };
    };
    requestBody?: {
      content: {
        "application/json": {
          /** Format: uri */
          url?: string;
          events?: string[];
          enabled?: boolean;
        };
      };
    };
    responses: {
      /** @description Updated endpoint */
      200: {
        content: {
          "application/json": components["schemas"]["WebhookEndpoint"];
        };
      };
    };
  };
  /**
   * Rotate webhook endpoint secret
   * @description Rotates the signing secret for a webhook endpoint while preserving its id.
   */
  rotateWebhookSecret: {
    parameters: {
      path: {
        endpoint_id: string;
      };
    };
    responses: {
      /** @description Secret rotated */
      200: {
        content: {
          "application/json": components["schemas"]["WebhookEndpoint"];
        };
      };
    };
  };
  /**
   * List audit log entries
   * @description Returns paginated audit log entries for compliance and monitoring.
   */
  listAuditLogs: {
    parameters: {
      query?: {
        actor_id?: string;
        resource_type?: string;
        resource_id?: string;
        created_before?: string;
        created_after?: string;
        cursor?: string;
        limit?: number;
      };
    };
    responses: {
      /** @description Audit log entries */
      200: {
        content: {
          "application/json": {
            data?: components["schemas"]["AuditLogEntry"][];
            meta?: components["schemas"]["PaginationMeta"];
          };
        };
      };
    };
  };
  /**
   * List recent events
   * @description Lists recent event payloads for dashboards or streaming.
   */
  listEvents: {
    parameters: {
      query?: {
        type?: string;
        limit?: number;
      };
    };
    responses: {
      /** @description Events page */
      200: {
        content: {
          "application/json": {
            data?: components["schemas"]["Event"][];
            meta?: components["schemas"]["PaginationMeta"];
          };
        };
      };
    };
  };
  /**
   * Retrieve theme configuration
   * @description Returns the hosted component theme configuration assigned to the project.
   */
  getThemeConfig: {
    responses: {
      /** @description Theme configuration */
      200: {
        content: {
          "application/json": components["schemas"]["ThemeConfig"];
        };
      };
    };
  };
  /**
   * Update theme configuration
   * @description Updates the theme configuration that powers hosted components.
   */
  updateThemeConfig: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["ThemeConfig"];
      };
    };
    responses: {
      /** @description Updated theme configuration */
      200: {
        content: {
          "application/json": components["schemas"]["ThemeConfig"];
        };
      };
    };
  };
  /**
   * Retrieve project configuration
   * @description Returns the project configuration used by APIs and dashboard flows.
   */
  getProjectConfig: {
    parameters: {
      query?: {
        domain?: string;
      };
      path: {
        project_id: string;
      };
    };
    responses: {
      /** @description Project */
      200: {
        content: {
          "application/json": components["schemas"]["Project"];
        };
      };
    };
  };
  /**
   * Update project configuration
   * @description Updates project-level configuration values and secrets.
   */
  updateProjectConfig: {
    parameters: {
      query?: {
        domain?: string;
      };
      path: {
        project_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": {
          default_auth_strategies?: string[];
          allowed_origins?: string[];
          jwt_template?: {
            ttl_seconds?: number;
            custom_claims?: Record<string, never>;
          };
          branding?: Record<string, never>;
        };
      };
    };
    responses: {
      /** @description Updated project */
      200: {
        content: {
          "application/json": components["schemas"]["Project"];
        };
      };
    };
  };
  /**
   * Delete project
   * @description Permanently deletes a project and all associated data.
   */
  deleteProject: {
    parameters: {
      path: {
        project_id: string;
      };
    };
    responses: {
      /** @description Project deleted */
      204: {
        content: never;
      };
    };
  };
  /**
   * Rotate signing keys
   * @description Rotates the signing keys and returns updated JWKS metadata.
   */
  rotateSigningKeys: {
    parameters: {
      query?: {
        domain?: string;
      };
      path: {
        project_id: string;
      };
    };
    responses: {
      /** @description JWKS rotated */
      201: {
        content: {
          "application/json": {
            /** Format: uri */
            jwks_uri?: string;
          };
        };
      };
    };
  };
  /**
   * List API keys
   * @description Lists publishable and secret API keys scoped to the project.
   */
  listApiKeys: {
    parameters: {
      query?: {
        domain?: string;
        environment?: "development" | "staging" | "production";
        type?: "publishable" | "secret";
      };
      path: {
        project_id: string;
      };
    };
    responses: {
      /** @description API keys */
      200: {
        content: {
          "application/json": {
            data?: components["schemas"]["APIKey"][];
          };
        };
      };
    };
  };
  /**
   * Create API key
   * @description Creates an API key scoped to the requested permissions and environment.
   */
  createApiKey: {
    parameters: {
      query?: {
        domain?: string;
      };
      path: {
        project_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": {
          /** @enum {string} */
          environment: "development" | "staging" | "production";
          /** @enum {string} */
          type: "publishable" | "secret";
          scopes?: string[];
          label?: string;
        };
      };
    };
    responses: {
      /** @description API key created */
      201: {
        content: {
          "application/json": components["schemas"]["APIKey"];
        };
      };
    };
  };
  /**
   * Revoke API key
   * @description Revokes an API key, preventing it from being used for authentication.
   */
  revokeApiKey: {
    parameters: {
      path: {
        project_id: string;
        key_id: string;
      };
    };
    responses: {
      /** @description API key revoked */
      204: {
        content: never;
      };
    };
  };
  /**
   * Rotate API key secret
   * @description Rotates the secret for an existing API key without changing the identifier.
   */
  rotateApiKeySecret: {
    parameters: {
      query?: {
        domain?: string;
      };
      path: {
        project_id: string;
        key_id: string;
      };
    };
    requestBody?: {
      content: {
        "application/json": {
          reason?: string;
        };
      };
    };
    responses: {
      /** @description API key rotated */
      200: {
        content: {
          "application/json": components["schemas"]["APIKey"];
        };
      };
    };
  };
  /**
   * Retrieve publishable configuration
   * @description Returns the publishable configuration consumed directly by browser-based clients.
   */
  getClientConfig: {
    responses: {
      /** @description Client config */
      200: {
        content: {
          "application/json": {
            project?: components["schemas"]["Project"];
            enabled_strategies?: string[];
          };
        };
      };
    };
  };
  /**
   * Create session during SSR
   * @description Creates a session while rendering on the server and returns the cookie payload.
   */
  createClientSession: {
    requestBody: {
      content: {
        "application/json": {
          user_id: string;
          organization_id?: string;
          /** Format: date-time */
          expires_at?: string;
        };
      };
    };
    responses: {
      /** @description Session created */
      201: {
        content: {
          "application/json": components["schemas"]["Session"];
        };
      };
    };
  };
  /**
   * Retrieve current session user
   * @description Returns the current session's user to light-weight server actions or clients.
   */
  getClientUser: {
    responses: {
      /** @description Current user */
      200: {
        content: {
          "application/json": {
            user?: components["schemas"]["User"];
            session?: components["schemas"]["Session"];
          };
        };
      };
    };
  };
  /**
   * Get user information
   * @description Returns OIDC compliant user information.
   */
  getUserInfo: {
    responses: {
      /** @description User information */
      200: {
        content: {
          "application/json": {
            sub?: string;
            name?: string;
            email?: string;
          };
        };
      };
    };
  };
  /**
   * List sessions
   * @description Retrieve all active sessions for the authenticated user.
   */
  listSessions: {
    responses: {
      /** @description List of sessions */
      200: {
        content: {
          "application/json": {
            data?: components["schemas"]["Session"][];
          };
        };
      };
    };
  };
  /**
   * Delete a session
   * @description Immediately revokes and deletes a session by ID.
   */
  deleteSession: {
    parameters: {
      path: {
        session_id: string;
      };
    };
    responses: {
      /** @description Session revoked */
      204: {
        content: never;
      };
    };
  };
  /**
   * Get usage statistics
   * @description Retrieve resource usage and quota consumption for the tenant.
   */
  getUsage: {
    responses: {
      /** @description Usage stats */
      200: {
        content: {
          "application/json": components["schemas"]["UsageResponse"];
        };
      };
    };
  };
  /**
   * List passkeys
   * @description Retrieve all registered passkeys for the authenticated user.
   */
  listPasskeys: {
    responses: {
      /** @description List of passkeys */
      200: {
        content: {
          "application/json": {
            data?: components["schemas"]["PasskeyCredential"][];
          };
        };
      };
    };
  };
  /**
   * Get WebAuthn registration options
   * @description Retrieve the options needed to register a new passkey.
   */
  getWebauthnRegistrationOptions: {
    responses: {
      /** @description Registration options */
      200: {
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  /**
   * Verify WebAuthn registration
   * @description Complete passkey registration by verifying the attestation.
   */
  verifyWebauthnRegistration: {
    requestBody?: {
      content: {
        "application/json": {
          [key: string]: unknown;
        };
      };
    };
    responses: {
      /** @description Verified */
      200: {
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  /**
   * List user identities
   * @description Retrieve all OAuth and email identities linked to a user.
   */
  listUserIdentities: {
    parameters: {
      path: {
        user_id: string;
      };
    };
    responses: {
      /** @description List of identities */
      200: {
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  /**
   * Delete OAuth identity
   * @description Unlink an OAuth identity from a user account.
   */
  deleteUserOAuthIdentity: {
    parameters: {
      path: {
        user_id: string;
        oauth_account_id: string;
      };
    };
    responses: {
      /** @description Identity deleted */
      204: {
        content: never;
      };
    };
  };
}
